---
title: "assignment"
author: "Rebecca Cockroft"
date: "2023-01-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1 (Merge)

Combining New York and Detroit purchases: 

```{r}
# loading required packages 

library(tidyverse)

# importing csv files 

ny <- read_csv("new_york_purchases.csv")
detroit <- read_csv("detroit_purchases.csv")

# not required but it might be a good idea to create another "location" variable
# by doing so we can tell which dataset it originally came from, and allows for future filtering 

ny$location <- "New York"
detroit$location <- "Detroit"

# let's check the data types to make sure they are the same for ny and detroit 

str(detroit)
str(ny)
```
```{r}

# converting ny timestamp to date/time (POSIX) format
# note that we must put the timezone as null, otherwise as.POSIXct will covert it from EST to UTC (which the detroit purchases are coded as)

ny$purchase_timestamp <- as.POSIXct(ny$purchase_timestamp, tz = "NULL")

# make amount numeric for detroit 

detroit$amount <- parse_number(detroit$amount)
  
# merging the datasets by appending them to each other 

full_data <- 
  rbind(detroit, ny) %>% 
  
  # dropping "id" column because it's redundant to R's index and is misaligned after merge 
  select(-id)

# previewing data 

head(full_data)
```

Normalizing type field to a product line: 

```{r}

# selecting rows with specific values and replacing "type" according to mapping 

full_data$type[full_data$type %in% c("cakes", "pizzas", "puffs")] <- "bakery"
full_data$type[full_data$type %in% c("milk", "cheese")] <- "dairy"
full_data$type[full_data$type %in% c("tomato", "carrot", "beans")] <- "vegetable"

# checking that only bakery, dairy, and vegatable remain in the data 

table(full_data$type)
```

## Problem 2 (Filter)

```{r}

# only selecting rows with timestamp on 1/2/2023

jan_two <- full_data %>%
  filter(as.Date(purchase_timestamp) == as.Date("2023-01-02"))
```

## Problem 3 (Graph)

### i. Total Revenue by Product Line 

```{r}

# creating barplot 

ggplot(
  
  # aggregating data to sum revenue by product line 
  
  jan_two %>% 
    group_by(type) %>% 
    summarize(amount = sum(amount)),
  
  # setting x-axis and color to product line, y to revenue
  
  aes(x=type, y=amount, fill = type)) +
  geom_bar(stat="identity") + 
  
  # relabeling categories and setting color palette 
  
  scale_fill_brewer(palette = "Set3",
                    labels = c('Bakery','Dairy','Vegetable')) + 
  scale_x_discrete(labels = c('Bakery','Dairy','Vegetable')) +
  
  # putting dollar labels on y-axis 
  
  scale_y_continuous(labels=scales::dollar_format()) + 
  
  # setting legend/x-axis/y-axis/title labels 
  
  labs(fill = "Product Line", 
       x = "Product Line", 
       y = "Revenue (USD)",
       title = "Total Revenue by Product Line on 1/2/2023") + 
  
  # setting theme 
  
  theme_classic()
```

### ii. Total Number of Items Purchased by Hour

```{r}

# creating histogram 

ggplot(jan_two, 
       
       # setting x-axis to purchase time 
       
       aes(x = purchase_timestamp)) + 
  
  # making the bin size 1 hour and setting colors 
  
  geom_histogram(binwidth = 3600,
                 boundary = 0, 
                 fill = "lightblue", 
                 color = "black") +
  
  # creating labels for each hour 
  
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M", expand = c(.05, 0, .01, 0)) +
  
  # setting x-axis/y-axis/title labels 
  
  labs(x = "Time", y = "Number of Purchases", title = "Purchases by Hour on 1/2/2023") + 
  
  # setting theme 
  
  theme_bw() +
  
  # rotating x-axis labels so they don't overlap 
  
  theme(axis.text.x = element_text(angle = 60, hjust=1)) 
```

